"""Tiền xử lý cho model — CHỦ SỞ HỮU: Thông (branch `ml-eng`).

Task T4. Sản phẩm: hai phiên bản X (scaled / unscaled) + Y_hidden tách riêng.
"""

from __future__ import annotations

import pandas as pd
from sklearn.preprocessing import StandardScaler

from . import config


def split_column_groups(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Tách thành ``(X, y_hidden, ids)``. T4.1 — ADR-006.

    ⚠️ ``y_hidden`` gồm cả ``end_x/end_y/end_z`` — vị trí bóng SAU khi sút,
    cũng là leakage. Rất hay bị quên.
    """
    ids = df[config.ID_COLS].copy()
    y_hidden = df[config.HIDDEN_COLS].copy()
    
    feature_cols = config.NUMERIC_FEATURES + config.CATEGORICAL_FEATURES + config.BOOL_FLAGS
    X = df[config.NUMERIC_FEATURES + config.CATEGORICAL_FEATURES + config.BOOL_FLAGS].copy()
    
    return X, y_hidden, ids


def encode_categoricals(X: pd.DataFrame) -> pd.DataFrame:
    """One-hot ``config.CATEGORICAL_FEATURES``. T4.2.

    Note: EDA của Phong (T2.3) có thể đề xuất gộp ``body_part == "Other"``
    (chỉ 7 shot ở World Cup 2018) để tránh cột gần như toàn 0 làm nhiễu khoảng cách L2.
    """
    X_encoded = pd.get_dummies(X, columns=config.CATEGORICAL_FEATURES, drop_first=False)
    
    # Convert booleans to int
    for col in config.BOOL_FLAGS:
        if col in X_encoded.columns:
            X_encoded[col] = X_encoded[col].astype(int)
            
    # Also convert boolean dummy columns generated by get_dummies to int
    for col in X_encoded.columns:
        if X_encoded[col].dtype == 'bool':
            X_encoded[col] = X_encoded[col].astype(int)
            
    return X_encoded


def handle_missing(X: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
    """Xử lý missing, trả ``(X_sạch, báo_cáo)``. T4.3.

    ``báo_cáo`` phải ghi số dòng/cột bị ảnh hưởng để đưa vào DECISIONS.md.
    Chú ý ``gk_*`` NaN khi freeze_frame không có GK.
    """
    report = {}
    X_clean = X.copy()
    
    if "keeper_x" in X_clean.columns:
        n_missing_x = int(X_clean["keeper_x"].isna().sum())
        if n_missing_x > 0:
            X_clean["keeper_x"] = X_clean["keeper_x"].fillna(120.0)
            report["keeper_x_imputed_with_120.0"] = n_missing_x
            
    if "keeper_y" in X_clean.columns:
        n_missing_y = int(X_clean["keeper_y"].isna().sum())
        if n_missing_y > 0:
            X_clean["keeper_y"] = X_clean["keeper_y"].fillna(40.0)
            report["keeper_y_imputed_with_40.0"] = n_missing_y
            
    for col in config.BOOL_FLAGS:
        if col in X_clean.columns:
            n_missing_bool = int(X_clean[col].isna().sum())
            if n_missing_bool > 0:
                X_clean[col] = X_clean[col].fillna(0)
                report[f"{col}_imputed_with_0"] = n_missing_bool
                
    return X_clean, report


def make_scaled_unscaled(X: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Trả ``(X_unscaled, X_scaled)`` — cùng index, cùng thứ tự cột. T4.4.

    ⚠️ Ghi rõ trong report: scaler fit trên toàn bộ dữ liệu hay chỉ trên train,
    và vì sao cách đó không gây leakage trong bối cảnh unsupervised.
    """
    X_unscaled = X.copy()
    
    from sklearn.preprocessing import RobustScaler
    scaler = RobustScaler()
    X_scaled_arr = scaler.fit_transform(X)
    X_scaled = pd.DataFrame(X_scaled_arr, columns=X.columns, index=X.index)
    
    return X_unscaled, X_scaled


def save_all(X_unscaled: pd.DataFrame, X_scaled: pd.DataFrame, y_hidden: pd.DataFrame, ids: pd.DataFrame) -> None:
    """Ghi ra ``config.DATA_PROCESSED`` kèm ``shot_id`` để join ngược. T4.5.

    Check: hai file X cùng số dòng, cùng thứ tự.
    """
    config.DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
    
    unscaled_out = pd.concat([ids, X_unscaled], axis=1)
    scaled_out = pd.concat([ids, X_scaled], axis=1)
    hidden_out = pd.concat([ids, y_hidden], axis=1)
    
    unscaled_out.to_csv(config.X_UNSCALED_CSV, index=False, encoding=config.CSV_ENCODING)
    scaled_out.to_csv(config.X_SCALED_CSV, index=False, encoding=config.CSV_ENCODING)
    hidden_out.to_csv(config.Y_HIDDEN_CSV, index=False, encoding=config.CSV_ENCODING)
